In [4]:
import numpy as np

In [16]:
x = np.arange(21)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [18]:
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
x[3::3]

array([ 3,  6,  9, 12, 15, 18])