In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [5]:
score = np.array([english_score, math_score, chinese_score])
score

array([[55., 89., 76., 65., 48., 70.],
       [60., 85., 60., 68., nan, 60.],
       [65., 90., 82., 72., 66., 77.]])

In [11]:
np.nanmean(score, axis = 1)

array([67.16666667, 66.6       , 75.33333333])

In [12]:
np.nanmax(score, axis = 1)

array([89., 85., 90.])

In [13]:
np.nanmin(score, axis = 1)

array([48., 60., 65.])

In [14]:
np.nanstd(score, axis = 1)

array([13.43399502,  9.70772888,  8.8254682 ])

In [15]:
score[1,4] = 55
score

array([[55., 89., 76., 65., 48., 70.],
       [60., 85., 60., 68., 55., 60.],
       [65., 90., 82., 72., 66., 77.]])

In [21]:
np.mean(score[1,])

64.66666666666667

In [19]:
np.max(score[1,])

85.0

In [20]:
np.min(score[1,])

55.0

In [22]:
np.std(score[1,])

9.860132971832694

In [23]:
np.corrcoef(score)

array([[1.        , 0.7855563 , 0.97792828],
       [0.7855563 , 1.        , 0.74056803],
       [0.97792828, 0.74056803, 1.        ]])